on:
  push:
    branches:
      - master
name:  Snap release
jobs:
  snap-release-job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
          use_lxd: true
      - name: Build snap
        run: sg lxd -c 'snapcraft --use-lxd' && snapcraft upload  --release=stable fuego_*.snap
